apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-conf
data:
  HADOOP_HOME: "/opt/hadoop"
  HADOOP_MAPRED_HOME: "/opt/hadoop"
  CORE-SITE.XML_fs.default.name: "hdfs://namenode"
  CORE-SITE.XML_fs.defaultFS: "hdfs://namenode"
  HDFS-SITE.XML_dfs.namenode.rpc-address: "namenode:8020"
  HDFS-SITE.XML_dfs.replication: "1"
  MAPRED-SITE.XML_mapreduce.framework.name: "yarn"
  MAPRED-SITE.XML_yarn.app.mapreduce.am.env: "HADOOP_MAPRED_HOME=$HADOOP_HOME"
  MAPRED-SITE.XML_mapreduce.map.env: "HADOOP_MAPRED_HOME=$HADOOP_HOME"
  MAPRED-SITE.XML_mapreduce.reduce.env: "HADOOP_MAPRED_HOME=$HADOOP_HOME"
  MAPRED-SITE.XML_mapreduce.application.classpath: "$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib-examples/*"
  YARN-SITE.XML_yarn.resourcemanager.hostname: "resourcemanager"
  YARN-SITE.XML_yarn.nodemanager.address: "nodemanager:45454"
  YARN-SITE.XML_yarn.nodemanager.pmem-check-enabled: "false"
  YARN-SITE.XML_yarn.nodemanager.delete.debug-delay-sec: "600"
  YARN-SITE.XML_yarn.nodemanager.vmem-check-enabled: "false"
  YARN-SITE.XML_yarn.nodemanager.aux-services: "mapreduce_shuffle"
  YARN-SITE.XML_yarn.nodemanager.env-whitelist: "JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_HOME,PATH,LANG,TZ,HADOOP_MAPRED_HOME"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.maximum-applications: "10000"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.maximum-am-resource-percent: "0.2"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.resource-calculator: "org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.queues: "default"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.capacity: "100"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.user-limit-factor: "1"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.maximum-capacity: "100"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.state: "RUNNING"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.acl_submit_applications: "*"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.acl_administer_queue: "*"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.node-locality-delay: "40"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.queue-mappings: ""
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.queue-mappings-override.enable: "false"
