apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv
  labels:
    type: datanode
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: datanode-storage
  local:
    path: /tmp/apache/datanode
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop

