apiVersion: v1
kind: Service
metadata:
  name: datanode-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: datanode # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 9864
      targetPort: 9864 # == pod template: spec ports container port
    - protocol: TCP
      name: transfer
      port: 9866
      targetPort: 9866
    - protocol: TCP
      name: ipc
      port: 9867
      targetPort: 9867
---
apiVersion: v1
kind: Service
metadata:
  name: datanode-nodeport
spec:
  type: NodePort
  selector:
    app: datanode # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 9864
      targetPort: 9864 # == pod template: spec ports container port
      nodePort: 30864 # The range of valid ports is 30000-32767

