apiVersion: v1
kind: Service
metadata:
  name: jobhistory-svc
spec:
  type: ClusterIP
  selector:
    app: jobhistory # == pod template: labels
  ports:
    - protocol: TCP
      name: jobhistory
      port: 10020
      targetPort: 10020 # == pod template: spec ports container port
    - protocol: TCP
      name: http
      port: 19888
      targetPort: 19888
    # - protocol: TCP
    #   name: https
    #   port: 19890
    #   targetPort: 19890
---
apiVersion: v1
kind: Service
metadata:
  name: jobhistory-nodeport
spec:
  type: NodePort
  selector:
    app: jobhistory # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 19888
      targetPort: 19888
      nodePort: 30888 # The range of valid ports is 30000-32767
    # - protocol: TCP
    #   name: https
    #   port: 19890
    #   targetPort: 19890
    #   nodePort: 30890 # The range of valid ports is 30000-32767

