apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobhistory
spec:
  serviceName: jobhistory-svc
  replicas: 1
  selector:
    matchLabels:
      app: jobhistory # == .spec.template.metadata.lables
  template:
    metadata:
      labels:
        app: jobhistory # == .spec.selector.matchLabels
    spec:
      hostname: jobhistory
      containers:
        - name: jobhistory
          image: apache/hadoop:3.3.6
          command:
            - /opt/starter.sh
            - mapred
            - historyserver
            - start
          ports:
            - name: jobhistory
              containerPort: 10020
            - name: http
              containerPort: 19888
            # - name: https
            #  containerPort: 19890
          envFrom:
            - configMapRef:
                name: hadoop-conf
---
apiVersion: v1
kind: Service
metadata:
  name: jobhistory-svc
spec:
  type: ClusterIP
  selector:
    app: jobhistory # == pod template: labels
  ports:
    - protocol: TCP
      name: jobhistory
      port: 10020
      targetPort: 10020 # == pod template: spec ports container port
    - protocol: TCP
      name: http
      port: 19888
      targetPort: 19888
    # - protocol: TCP
    #   name: https
    #   port: 19890
    #   targetPort: 19890
---
apiVersion: v1
kind: Service
metadata:
  name: jobhistory-nodeport
spec:
  type: NodePort
  selector:
    app: jobhistory # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 19888
      targetPort: 19888
      nodePort: 30888 # The range of valid ports is 30000-32767
    # - protocol: TCP
    #   name: https
    #   port: 19890
    #   targetPort: 19890
    #   nodePort: 30890 # The range of valid ports is 30000-32767
