apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  selector:
    matchLabels:
      app: namenode # == .spec.template.metadata.lables
  template:
    metadata:
      labels:
        app: namenode # == .spec.selector.matchLabels
    spec:
      hostname: namenode
      containers:
        - name: namenode
          image: apache/hadoop:3.3.6
          command:
            - /opt/starter.sh
            - hdfs
            - namenode
          ports:
            - name: rpc
              containerPort: 8020
            - name: http
              containerPort: 9870
          env:
            - name: HADOOP_HOME
              value: "/opt/hadoop"
            - name: ENSURE_NAMENODE_DIR
              value: "/tmp/hadoop-root/dfs/name"
          envFrom:
            - configMapRef:
                name: hadoop-conf
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    app: namenode # == pod template: labels
  ports:
    - protocol: TCP
      name: rpc
      port: 8020
      targetPort: 8020 # == pod template: spec ports container port
    - protocol: TCP
      name: http
      port: 9870
      targetPort: 9870
      nodePort: 30870 # The range of valid ports is 30000-32767

