apiVersion: v1
kind: Service
metadata:
  name: namenode-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: namenode # == pod template: labels
  ports:
    - protocol: TCP
      name: rpc
      port: 8020
      targetPort: 8020 # == pod template: spec ports container port
    - protocol: TCP
      name: http
      port: 9870
      targetPort: 9870
---
apiVersion: v1
kind: Service
metadata:
  name: namenode-nodeport
spec:
  type: NodePort
  selector:
    app: namenode # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 9870
      targetPort: 9870
      nodePort: 30870 # The range of valid ports is 30000-32767
