apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
  labels:
    type: namenode
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode-storage
  hostPath:
    # It is not based on the path of the host machine.
    # This is the internal virtual path of a local k8s cluster process
    # such as docker-desktop or minikube.
    path: /tmp/apache/namenode
    type: DirectoryOrCreate

