apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
  labels:
    type: namenode
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: namenode-storage
  local:
    path: /tmp/apache/namenode
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop

