apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: resourcemanager # == pod template: labels
  ports:
    - protocol: TCP
      name: scheduler
      port: 8030
      targetPort: 8030 # == pod template: spec ports container port
    - protocol: TCP
      name: tracker
      port: 8031
      targetPort: 8031
    - protocol: TCP
      name: rpc
      port: 8032
      targetPort: 8032
    - protocol: TCP
      name: admin
      port: 8033
      targetPort: 8033
    - protocol: TCP
      name: http
      port: 8088
      targetPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-nodeport
spec:
  type: NodePort
  selector:
    app: resourcemanager # == pod template: labels
  ports:
    - protocol: TCP
      name: http
      port: 8088
      targetPort: 8088
      nodePort: 30088 # The range of valid ports is 30000-32767

