apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resourcemanager
spec:
  serviceName: resourcemanager-svc
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager # == .spec.template.metadata.lables
  template:
    metadata:
      labels:
        app: resourcemanager # == .spec.selector.matchLabels
    spec:
      containers:
        - name: resourcemanager
          image: apache/hadoop:3.3.6
          command:
            - /opt/starter.sh
            - yarn
            - resourcemanager
          ports:
            - name: scheduler
              containerPort: 8030
            - name: tracker
              containerPort: 8031
            - name: rpc
              containerPort: 8032
            - name: admin
              containerPort: 8033
            - name: http
              containerPort: 8088
          envFrom:
            - configMapRef:
                name: hadoop-conf

